name = "sell2sr1"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
RESEND_API_KEY = "re_tELAVhxT_53N76tMzwN6Pt1JzkVyQKQSsj9"
CONFIRMATION_FROM_EMAIL = "appraisals@sr1companies.com"
