name = "sell2sr1"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

# Optional Cloudflare R2 Bucket for photos
# [[r2_buckets]]
# binding = 'PHOTOS_BUCKET'
# bucket_name = 'sell2sr1-photos'

# Optional Cloudflare D1 SQL database
# [[d1_databases]]
# binding = "DB"
# database_name = "sell2sr1-db"
# database_id = "xxxx-xxxx-xxxx"
